'use client';

import React from 'react';
import { AlertTriangle, ShieldAlert, CheckCircle2, RefreshCw, Filter, Clock, Info } from 'lucide-react';
import type { AlertItem } from '@/types/api';

export function AlertsView() {
  const [alerts, setAlerts] = React.useState<AlertItem[]>([]);
  const [loading, setLoading] = React.useState<boolean>(true);
  const [severityFilter, setSeverityFilter] = React.useState<string>('all');
  const [statusFilter, setStatusFilter] = React.useState<string>('all');

  const fetchAlerts = async () => {
    try {
      setLoading(true);
      const token = typeof window !== 'undefined' ? localStorage.getItem('radius_token') : null;
      const headers: Record<string, string> = {};
      if (token) headers['Authorization'] = `Bearer ${token}`;

      let url = '/api/alerts?limit=100';
      if (severityFilter !== 'all') url += `&severity=${severityFilter}`;
      if (statusFilter !== 'all') url += `&status=${statusFilter}`;

      const res = await fetch(url, { headers });
      if (res.ok) {
        const json = await res.json();
        setAlerts(json.data?.items || json.data || []);
      }
    } catch {} finally {
      setLoading(false);
    }
  };

  React.useEffect(() => {
    fetchAlerts();
  }, [severityFilter, statusFilter]);

  const handleUpdateStatus = async (id: number, status: 'acknowledged' | 'resolved') => {
    try {
      const token = typeof window !== 'undefined' ? localStorage.getItem('radius_token') : null;
      const headers: Record<string, string> = { 'Content-Type': 'application/json' };
      if (token) headers['Authorization'] = `Bearer ${token}`;

      await fetch(`/api/alerts/${id}`, {
        method: 'PATCH',
        headers,
        body: JSON.stringify({ status }),
      });
      fetchAlerts();
    } catch {}
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-foreground flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-amber-500" />
            <span>NOC System & Operational Alerts</span>
          </h2>
          <p className="text-xs text-muted-foreground mt-0.5">
            Active and historical alerts generated by FreeRADIUS daemons, BNG status probes, and IP pool exhaustion monitors.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={fetchAlerts}
            disabled={loading}
            className="p-2 rounded-xl border border-border bg-card hover:bg-muted text-muted-foreground hover:text-foreground text-xs font-medium flex items-center gap-1.5 transition-colors"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
            <span>Refresh</span>
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="p-4 rounded-2xl border border-border bg-card shadow-sm flex flex-wrap items-center justify-between gap-3 text-xs">
        <div className="flex items-center gap-2">
          <Filter className="w-3.5 h-3.5 text-muted-foreground" />
          <span className="font-semibold text-foreground">Filter Severity:</span>
          {['all', 'critical', 'warning', 'info'].map((s) => (
            <button
              key={s}
              onClick={() => setSeverityFilter(s)}
              className={`px-2.5 py-1 rounded-lg capitalize font-medium transition-colors ${
                severityFilter === s
                  ? 'bg-primary text-primary-foreground font-semibold shadow-sm'
                  : 'bg-muted/50 hover:bg-muted text-muted-foreground hover:text-foreground'
              }`}
            >
              {s}
            </button>
          ))}
        </div>

        <div className="flex items-center gap-2">
          <span className="font-semibold text-foreground">Status:</span>
          {['all', 'active', 'acknowledged', 'resolved'].map((st) => (
            <button
              key={st}
              onClick={() => setStatusFilter(st)}
              className={`px-2.5 py-1 rounded-lg capitalize font-medium transition-colors ${
                statusFilter === st
                  ? 'bg-primary text-primary-foreground font-semibold shadow-sm'
                  : 'bg-muted/50 hover:bg-muted text-muted-foreground hover:text-foreground'
              }`}
            >
              {st}
            </button>
          ))}
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-3">
        {loading && alerts.length === 0 ? (
          <div className="py-12 text-center text-muted-foreground">
            <RefreshCw className="w-6 h-6 animate-spin mx-auto mb-2 text-primary" />
            <span>Loading system alerts...</span>
          </div>
        ) : alerts.length === 0 ? (
          <div className="py-12 text-center text-muted-foreground border border-border rounded-2xl bg-card">
            <CheckCircle2 className="w-8 h-8 mx-auto mb-2 text-emerald-500" />
            <p className="font-medium text-sm text-foreground">No alerts matching current filters.</p>
            <p className="text-xs text-muted-foreground mt-0.5">All monitored systems are within operational bounds.</p>
          </div>
        ) : (
          alerts.map((a) => (
            <div
              key={a.id}
              className={`p-4 rounded-2xl border transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                a.severity === 'critical'
                  ? 'bg-rose-500/5 border-rose-500/25 hover:border-rose-500/50'
                  : a.severity === 'warning'
                  ? 'bg-amber-500/5 border-amber-500/25 hover:border-amber-500/50'
                  : 'bg-card border-border hover:border-primary/40'
              }`}
            >
              <div className="flex items-start gap-3">
                <div
                  className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ${
                    a.severity === 'critical'
                      ? 'bg-rose-500/10 text-rose-500 border border-rose-500/20'
                      : a.severity === 'warning'
                      ? 'bg-amber-500/10 text-amber-500 border border-amber-500/20'
                      : 'bg-primary/10 text-primary border border-primary/20'
                  }`}
                >
                  {a.severity === 'critical' ? (
                    <ShieldAlert className="w-4 h-4" />
                  ) : a.severity === 'warning' ? (
                    <AlertTriangle className="w-4 h-4" />
                  ) : (
                    <Info className="w-4 h-4" />
                  )}
                </div>

                <div className="space-y-0.5">
                  <div className="flex items-center gap-2">
                    <h4 className="font-bold text-sm text-foreground">{a.title}</h4>
                    <span
                      className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider border ${
                        a.status === 'active'
                          ? 'bg-rose-500/10 text-rose-500 border-rose-500/20'
                          : a.status === 'acknowledged'
                          ? 'bg-amber-500/10 text-amber-500 border-amber-500/20'
                          : 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20'
                      }`}
                    >
                      {a.status}
                    </span>
                    <span className="text-[10px] text-muted-foreground uppercase font-mono">Source: {a.source}</span>
                  </div>
                  <p className="text-xs text-muted-foreground">{a.description}</p>
                  <div className="text-[10px] text-muted-foreground/80 flex items-center gap-2 pt-1 font-mono">
                    <span className="flex items-center gap-1">
                      <Clock className="w-3 h-3" /> {new Date(a.created_at).toLocaleString()}
                    </span>
                    {a.resolved_at && (
                      <span>• Resolved {new Date(a.resolved_at).toLocaleString()} by {a.resolved_by || 'admin'}</span>
                    )}
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              {a.status !== 'resolved' && (
                <div className="flex items-center gap-2 shrink-0">
                  {a.status === 'active' && (
                    <button
                      onClick={() => handleUpdateStatus(a.id, 'acknowledged')}
                      className="px-3 py-1.5 rounded-xl border border-border bg-card hover:bg-muted text-foreground text-xs font-medium transition-colors"
                    >
                      Acknowledge
                    </button>
                  )}
                  <button
                    onClick={() => handleUpdateStatus(a.id, 'resolved')}
                    className="px-3 py-1.5 rounded-xl bg-emerald-500 text-white hover:bg-emerald-600 text-xs font-semibold shadow-sm transition-all"
                  >
                    Resolve
                  </button>
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
}
